services:
  trigon:
    environment:
      - GOPATH=/settings/go
      - PATH=/usr/local/go/bin:/root/go/bin:/settings/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - ${SECURITY_RESULTS_DIR}:/security/results
      - ${WORDLISTS_DIR}:/security/wordlists
    cap_add:
      - NET_RAW
      - NET_ADMIN
